# Home Mac Setup - run 'be rake db:setup' when changing locs
# ======================
development:
  adapter: postgresql
  encoding: unicode
  database: chattr_development
  pool: 5
  username: aaron
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: chattr_test
  pool: 5
  username: aaron
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: chattr_production
  pool: 5
  username: aaron
  password:

# a/A setup - run 'be rake db:setup' when changing locs
# ======================
# development:
#   adapter: postgresql
#   encoding: unicode
#   database: chattr_development
#   pool: 5
#   username: appacademy
#   password:
#
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: chattr_test
#   pool: 5
#   username: appacademy
#   password:
#
# production:
#   adapter: postgresql
#   encoding: unicode
#   database: chattr_production
#   pool: 5
#   username: appacademy
#   password: